task:
  description: use RL methods to optimize traffic signal control problems
  task_name: tsc

world:
# necessary and distinctive parameters for simulators
  interval: 1.0
  seed: 0
  dir: data/

  saveReplay: True
  report_log_mode: normal # cbengine
  report_log_rate: 10

  no_warning: True
  gui: False

  rlTrafficLight: True

trainer:
  thread: 4
  ngpu: -1
  learning_start: 5000
  buffer_size: 5000
  steps: 3600
  test_steps: 3600
  yellow_length: 5
  action_interval: 10
  episodes: 200
  update_model_rate: 1
  update_target_rate: 10
  test_when_train: True

model:
  name: "non-rl"
  train_model: False
  test_model: True
  load_model: False
  graphic: False
  vehicle_max: 1 # TODO: what is this for
  learning_rate: 0.001
  batch_size: 64
  gamma: 0.95
  epsilon: 0.5
  epsilon_decay: 0.99
  epsilon_min: 0.05
  grad_clip: 5.0

  one_hot: False
  phase: False

logger:
  root_dir: "data/output_data/"
  log_dir: "logger/"
  replay_dir: "replay/"
  model_dir: "model/"
  data_dir: "dataset/"
  save_model: True
  save_rate: 5





