includes:
  - configs/agents/tsc/base.yml

model:
  name: frap
  n_layers: 2
  rotation: true
  conflict_matrix: true
  merge: multiply
  d_dense: 20
  learning_rate: 0.001
  batch_size: 64
  gamma: 0.95
  epsilon: 0.1
  epsilon_decay: 0.995
  epsilon_min: 0.01
  grad_clip: 5.0

trainer: 
  thread: 4 
  ngpu: -1 
  learning_start: 1000
  buffer_size: 5000 
  steps: 3600 
  test_steps: 3600 
<<<<<<< HEAD
  action_interval: 20
  episodes: 200
  update_model_rate: 1
  update_target_rate: 10
=======
  action_interval: 20 
  episodes: 100
  update_model_rate: 60
  update_target_rate: 80
>>>>>>> c9e0f6d3a23887a5f24015a4ed75bf97be5217de
  # loss_function: mean_squared_error

logger:
  log_dir: "logger"
  replay_dir: "replay"
  save_dir: "model"
  data_dir: "dataset"
  get_attention: False
  save_model: True
  save_rate: 20
  train_model: True
  test_model: True
  load_model: False

traffic:
  one_hot: True
  phase: True
  n_leg: 4
  thread_num: 4
  debug: False

  dic_feature_dim:
    d_cur_phase: !!python/tuple [8]
    d_lane_num_vehicle: !!python/tuple [12]

  list_state_feature: 
    - cur_phase
    # - time_this_phase
    # - vehicle_position_img
    # - vehicle_speed_img
    # - vehicle_acceleration_img
    # - vehicle_waiting_time_img
    - lane_num_vehicle
    # - lane_num_vehicle_been_stopped_thres01
    # - lane_num_vehicle_been_stopped_thres1
    # - lane_queue_length
    # - lane_num_vehicle_left
    # - lane_sum_duration_vehicle_left
    # - lane_sum_waiting_time
    # - terminal
    # - coming_vehicle
    # - leaving_vehicle
    # - pressure
    # - adjacency_matrix

  # lane_num: 
  #   left: 1
  #   right: 1
  #   straight: 1

  phases: ['NT_ST','WT_ET','NL_SL','WL_EL','NL_NT','SL_ST','WL_WT','EL_ET']
  
  list_lane_order: ['ET','EL','ST','SL','WT','WL','NT','NL']

  phase_expansion: {
    1: [0, 0, 1, 0, 0, 0, 1, 0],
    2: [1, 0, 0, 0, 1, 0, 0, 0],
    3: [0, 0, 0, 1, 0, 0, 0, 1],
    4: [0, 1, 0, 0, 0, 1, 0, 0],
    5: [0, 0, 0, 0, 0, 0, 1, 1],
    6: [0, 0, 1, 1, 0, 0, 0, 0],
    7: [0, 0, 0, 0, 1, 1, 0, 0],
    8: [1, 1, 0, 0, 0, 0, 0, 0]
  }

  phase_expansion_4_lane: {1: [0,0,1,1],2: [1,1,0,0]}