includes:
  - configs/tsc/rl.yml


model:
  name: colight
  graphic: True
  phase: False
  vehicle_max: 1
  epsilon: 0.8
  epsilon_decay: 0.9995
  epsilon_min: 0.01
  attention: False
  model_dict: {
  NEIGHBOR_NUM: 4,
  NEIGHBOR_EDGE_NUM: 4,
  N_LAYERS: 1,
  INPUT_DIM: [128, 128],
  OUTPUT_DIM: [128, 128],
  NODE_EMB_DIM: [128, 128],
  NUM_HEADS: [5, 5],
  NODE_LAYER_DIMS_EACH_HEAD: [16, 16],
  OUTPUT_LAYERS: []
  }

trainer:
  learning_start: 1000
